version: '3'
 
services:
  db:
    container_name: pg_piggyoink
    build: 
      context: ./docker/db/
      dockerfile: Dockerfile 
    restart: always
    environment:
      - TZ=Asia/Singapore
      - POSTGRES_DB=piggyoink
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password0000 
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 15432:5432
    networks:
      - gateway

volumes:
  pgdata:

networks:
  gateway:
